Vue training 04 - Filter logic
wolox-training/resm-react pull request #27
Opened 2019-04-24 16:29 UTC by rsuescun

## Summary

-Logic for filter the list of technologies was added

## Screenshots

![2019-04-23 18 57 36](https://user-images.githubusercontent.com/822241/56676531-1aa13700-6684-11e9-84d2-f055e5da20d0.gif)

## Trello Card

https://trello.com/c/I5xpeJLI/16-filter

2019-04-25 19:02 UTC, FrankIglesias requested changes

2019-04-25 19:02 UTC, FrankIglesias commented on vue-training/src/components/MessageNoData.vue
> +    width: 70%;
why this value?

2019-04-25 19:02 UTC, FrankIglesias commented on vue-training/src/components/TechTitle.vue
> +  h2.title
Do you think this should be a component?

2019-04-25 19:02 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +    filterCountSuffix: 'Tecnología(s)',
Do not use the data as translation constants. Write them in plain pug and afterwards will be moved to i18n

2019-04-25 19:02 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +
remove extra line

2019-04-25 19:02 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      const countOfTechs = this.filterTechs && this.filterTechs.map(techGroup => techGroup && techGroup.techsList.length)
filteredTechs?

2019-04-25 19:02 UTC, FrankIglesias commented on vue-training/src/views/index/index.pug
> +          span.filter-count {{ countTechs }} {{ filterCountSuffix }}
use | for this interpolations

2019-04-25 20:22 UTC, rsuescun commented on vue-training/src/components/TechTitle.vue
> +  h2.title
I think it's a good idea to have pieces of design and / or functionality separated into components.

But I do not know in real projects what is better for the performance of the app.

2019-04-25 20:22 UTC, rsuescun commented on vue-training/src/components/TechTitle.vue
> +  h2.title
In any case, I already eliminated this component.

2019-04-25 20:24 UTC, rsuescun commented on vue-training/src/components/MessageNoData.vue
> +    width: 70%;
It was an arbitrary value. I changed it to 'max-width: 600px;' and 'width: 100%;'

2019-04-26 00:08 UTC, FrankIglesias requested changes

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/components/MessageNoData.vue
> +<template lang="pug">
This should not be a component. It doesn't have any logic at all

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +
remove this line

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      const countOfTechs = this.filteredTechs && this.filteredTechs.map(techGroup => techGroup && techGroup.techsList.length)
Define a default value to `this.filteredTech` to avoid `&&` (same for techGroup)

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      if (countOfTechs && countOfTechs.length > 0 && countOfTechs.reduce) {
why the last .reduce?

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      if (countOfTechs && countOfTechs.length > 0 && countOfTechs.reduce) {
Remove the > 0

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      if (countOfTechs && countOfTechs.length > 0 && countOfTechs.reduce) {
remove the countOfTechs condition

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      let newTechs = this.techs
This will always be an array

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +      return this.countTechs > 0
you can return the this.countTechs instead as 0 is falsy already

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.js
> +    haveData() {
Maybe a computed is not needed here

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.pug
> +      .main(v-if="haveData")
single comma here

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.pug
> +          v-for="(techGroup, index) in filteredTechs"
single comma

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.pug
> +      message-no-data(v-else) No se encontraron techs
This should not be a component

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.pug
> +          .title {{ techGroup.title }}
use a h1 here

2019-04-26 00:08 UTC, FrankIglesias commented on vue-training/src/views/index/index.pug
> +          input.filter-input(type="text" placeholder="Filtrar" v-model="filter")
single comma after v-model

2019-04-29 15:11 UTC, FrankIglesias approved these changes

2019-04-30 21:03 UTC, merged