Content layout - List of tech-box for front and back sections with flex-wrap
wolox-training/resm-react pull request #5
Opened 2018-10-26 20:25 UTC by rsuescun

## Summary
- Added tech-box-list style to show box-tech in flex wrap
- Added all tech logos

## Screenshot
![image](https://user-images.githubusercontent.com/822241/47590831-36c15700-d933-11e8-9f87-88fa198209db.png)

## Trello card
https://trello.com/c/u3Gjxgzy/23-content-layout

2018-10-27 00:00 UTC, FrankIglesias requested changes

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/react_icon.svg" alt="Logo React">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/angular_icon.svg" alt="Logo AngularJS">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/vue_icon.svg" alt="Logo VueJS">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/elm_icon.svg" alt="Logo Elm">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/polymer_icon.svg" alt="Logo Polymer">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/rails_icon.png" alt="Logo Ruby on Rails">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/express_icon.svg" alt="Logo NodeJS">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/aspnet_icon.png" alt="Logo ASP.NET Core">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on index.html
> +        <img class="tech-box-logo" src="assets/tech/django_icon.svg" alt="Logo Django">
add slash before >

2018-10-27 00:00 UTC, FrankIglesias commented on scss/tech.scss
> +      left:0;
add space before the 0

2018-10-29 21:01 UTC, FrankIglesias approved these changes

2018-10-29 21:56 UTC, jmtov approved these changes
Excellent job! 🤙I just left a small comment. 😺

2018-10-29 21:56 UTC, jmtov commented on scss/tech.scss
> +  padding-left: 50px;
Try to make paddings and margins as symmetric as possible. This can help you handle LTR and RTL writing systems in the best way! 🙂

2018-10-30 13:57 UTC, mmamaniwolox requested changes

2018-10-30 13:57 UTC, mmamaniwolox commented on index.html
> +<body class="padding-app">
This is not very descriptive, you can write something like `app-container` or someting like that

2018-10-30 13:57 UTC, mmamaniwolox commented on index.html
> +      <img class="tech-box-logo" src="assets/tech/angular_icon.svg" alt="Logo AngularJS"/>
Same than previous PR, in english the word `logo` should be after the name of the tech

2018-10-30 13:57 UTC, mmamaniwolox commented on index.html
> +  <h1 class="title">Back-End Tools</h1>
It is supposed to be only one `h1` in a single screen, you should use `h2`

2018-10-30 16:28 UTC, mmamaniwolox approved these changes

2018-10-31 16:53 UTC, merged