CSS Transitions - Added transitions effect to tech-box
wolox-training/resm-react pull request #6
Opened 2018-10-29 15:53 UTC by rsuescun

## Summary
- Added transitions to tech-box, with animation effect, for 'hover' event
- Included all corrections from previous branches

## Screenshot
![image](https://user-images.githubusercontent.com/822241/47662292-a3716700-db68-11e8-9b08-79b3cc1df673.png)

## Trello card
https://trello.com/c/5N9R7SY4/25-css-transitions

2018-10-29 19:21 UTC, FrankIglesias requested changes

2018-10-29 19:21 UTC, FrankIglesias commented on scss/tech.scss
> +      z-index: -2;
why -2?

2018-10-29 21:00 UTC, FrankIglesias approved these changes

2018-10-29 22:06 UTC, jmtov approved these changes
Good job! Approved! 😸

2018-10-29 22:06 UTC, jmtov commented on scss/tech.scss
> +      transition: transform 0.5s ease;
Nice approach! 🤙

2018-10-30 13:57 UTC, mmamaniwolox approved these changes

2018-10-31 16:57 UTC, merged