Navbar - Added navbar styles
wolox-training/resm-react pull request #7
Opened 2018-10-29 18:17 UTC by rsuescun

## Summary
- Added navbar with logo and text
- Included all corrections from previous branches

## Screenshot
![image](https://user-images.githubusercontent.com/822241/47671100-d6255a80-db7c-11e8-8da1-1935cc6786c9.png)

## Trello card
https://trello.com/c/962MC2E8/13-navbar

2018-10-29 19:20 UTC, FrankIglesias requested changes

2018-10-29 19:20 UTC, FrankIglesias commented on scss/navbar.scss
> +  z-index: 9999;
why not 1 instead

2018-10-29 21:00 UTC, FrankIglesias requested changes

2018-10-29 21:00 UTC, FrankIglesias commented on scss/styles.scss
> +  padding: ($nav-height + 10) 20px 20px;
10px I think

2018-10-29 22:37 UTC, jmtov approved these changes
Great job! 😺

2018-10-29 22:37 UTC, jmtov commented on index.html
> +    <img class="navbar-logo" src="assets/wolox_logo.svg" alt="Logo App"/>
Nice job naming these classes! 🤓

2018-10-29 23:20 UTC, FrankIglesias approved these changes

2018-10-30 14:00 UTC, mmamaniwolox requested changes

2018-10-30 14:00 UTC, mmamaniwolox commented on index.html
> +  <header class="navbar">
We usually rather using `<nav>` instead of `header`

2018-10-30 14:00 UTC, mmamaniwolox commented on scss/navbar.scss
> +  flex-direction: row;
This is default prop, you dont need to write it down

2018-10-30 14:00 UTC, mmamaniwolox commented on scss/navbar.scss
> +  .navbar-logo {
Remember trying not to nest styles :P

2018-10-30 16:28 UTC, mmamaniwolox approved these changes

2018-10-31 16:57 UTC, merged